x-afisha-env: &afisha_env
  APP__HOST: 0.0.0.0
  APP__PORT: 8000
  APP__RELOAD: true
  POSTGRES__HOST: db
  POSTGRES__PORT: 5432
  POSTGRES__USER: postgres
  POSTGRES__PASSWORD: postgres
  POSTGRES__DATABASE: postgres
  POSTGRES__ECHO: false
  POSTGRES__POOL_SIZE: 10
  POSTGRES__MAX_OVERFLOW: 20
  REDIS__HOST: redis
  REDIS__PORT: 6379
  REDIS__DATABASE: 0
  REPORT__STORAGE_PATH: ./storage/reports
  TASKIQ__ADMIN_URL: http://afisha-taskiq-admin:3000
  CONNECTORS__PAYMENT__BASE_URL: http://payment-api:9001
  CONNECTORS__PROTECTION__BASE_URL: http://protection-api:9002
  KAFKA__BOOTSTRAP_SERVERS: localhost:9092
  KAFKA__PURCHASE_TOPIC: tickets.purchased
  PROJECT__NAME: Afisha
  PROJECT__ENV: development
  BOOKING__TTL_MINUTES: 15

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "7432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  payment-api:
    build: ./mock_apis/payment
    ports:
      - "9001:9001"

  protection-api:
    build: ./mock_apis/protection
    ports:
      - "9002:9002"

  redis:
    image: redis:7-alpine
    ports:
      - "7379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: bitnamilegacy/kafka:3.7
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:29092,CONTROLLER://:9093,EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka

  kafka-init:
    image: bitnamilegacy/kafka:3.7
    depends_on:
      - kafka
    command:
      - /bin/bash
      - -lc
      - |
        KAFKA_TOPICS=/opt/bitnami/kafka/bin/kafka-topics.sh
        for i in {1..30}; do
          $$KAFKA_TOPICS --bootstrap-server kafka:29092 --list >/dev/null 2>&1 && break
          sleep 2
        done
        $$KAFKA_TOPICS --bootstrap-server kafka:29092 --create --if-not-exists --topic tickets.purchased --partitions 2 --replication-factor 1
        $$KAFKA_TOPICS --bootstrap-server kafka:29092 --alter --topic tickets.purchased --partitions 2 || true

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: afisha-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - "8080:8080"

  redis-test:
    image: redis:7-alpine
    ports:
      - "7479:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  afisha-taskiq-admin:
    image: ghcr.io/taskiq-python/taskiq-admin:latest
    ports:
      - "3000:3000"
    environment:
      TASKIQ_ADMIN_API_TOKEN: supersecret
    volumes:
      - afisha_taskiq_admin_data:/usr/database/

  afisha-taskiq-cpu-worker:
    build:
      context: .
    command: taskiq worker afisha.infrastructure.tasks.taskiq_app:broker_cpu afisha.infrastructure.tasks.taskiq_tasks --log-level INFO --workers 2 --max-async-tasks 1 --max-prefetch 1
    environment:
      <<: *afisha_env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      afisha-taskiq-admin:
        condition: service_started
    volumes:
      - ./storage/reports:/app/storage/reports

  afisha-taskiq-io-worker:
    build:
      context: .
    command: taskiq worker afisha.infrastructure.tasks.taskiq_app:broker_io afisha.infrastructure.tasks.taskiq_tasks --log-level INFO --workers 1
    environment:
      <<: *afisha_env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      afisha-taskiq-admin:
        condition: service_started

  afisha-taskiq-scheduler:
    build:
      context: .
    command: taskiq scheduler afisha.infrastructure.tasks.taskiq_app:scheduler afisha.infrastructure.tasks.taskiq_tasks
    environment:
      <<: *afisha_env
    depends_on:
      redis:
        condition: service_healthy
#  app:
#    build: .
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/app
#      - .venv:/app/.venv
#    depends_on:
#      db:
#        condition: service_healthy
#      payment-api:
#        condition: service_started
#      protection-api:
#        condition: service_started
#     redis:
#       condition: service_healthy

volumes:
  postgres_data:
  kafka_data:
  afisha_taskiq_admin_data:
